import type { AuthRole, PermissionKey } from "@/types/auth";

export const permissions = {
  dashboardView: "dashboard:view",
  patientsView: "patients:view",
  patientsWrite: "patients:write",
  scheduleView: "schedule:view",
  scheduleWrite: "schedule:write",
  crmView: "crm:view",
  crmWrite: "crm:write",
  clinicalView: "clinical:view",
  clinicalWrite: "clinical:write",
  settingsView: "settings:view",
} satisfies Record<string, PermissionKey>;

export const rolePermissions: Record<AuthRole, PermissionKey[]> = {
  owner: [
    permissions.dashboardView,
    permissions.patientsView,
    permissions.patientsWrite,
    permissions.scheduleView,
    permissions.scheduleWrite,
    permissions.crmView,
    permissions.crmWrite,
    permissions.clinicalView,
    permissions.clinicalWrite,
    permissions.settingsView,
  ],
  admin: [
    permissions.dashboardView,
    permissions.patientsView,
    permissions.patientsWrite,
    permissions.scheduleView,
    permissions.scheduleWrite,
    permissions.crmView,
    permissions.crmWrite,
    permissions.clinicalView,
    permissions.clinicalWrite,
    permissions.settingsView,
  ],
  manager: [
    permissions.dashboardView,
    permissions.patientsView,
    permissions.patientsWrite,
    permissions.scheduleView,
    permissions.scheduleWrite,
    permissions.crmView,
    permissions.crmWrite,
    permissions.clinicalView,
    permissions.clinicalWrite,
    permissions.settingsView,
  ],
  clinician: [
    permissions.dashboardView,
    permissions.patientsView,
    permissions.scheduleView,
    permissions.scheduleWrite,
    permissions.clinicalView,
    permissions.clinicalWrite,
  ],
  physician: [
    permissions.dashboardView,
    permissions.patientsView,
    permissions.scheduleView,
    permissions.scheduleWrite,
    permissions.clinicalView,
    permissions.clinicalWrite,
  ],
  nutritionist: [
    permissions.dashboardView,
    permissions.patientsView,
    permissions.scheduleView,
    permissions.scheduleWrite,
    permissions.clinicalView,
    permissions.clinicalWrite,
  ],
  assistant: [
    permissions.dashboardView,
    permissions.patientsView,
    permissions.patientsWrite,
    permissions.scheduleView,
    permissions.scheduleWrite,
    permissions.crmView,
    permissions.crmWrite,
  ],
  reception: [
    permissions.dashboardView,
    permissions.patientsView,
    permissions.patientsWrite,
    permissions.scheduleView,
    permissions.scheduleWrite,
  ],
  sales: [
    permissions.dashboardView,
    permissions.crmView,
    permissions.crmWrite,
  ],
  nursing: [
    permissions.dashboardView,
    permissions.patientsView,
    permissions.scheduleView,
    permissions.scheduleWrite,
    permissions.clinicalView,
    permissions.clinicalWrite,
  ],
  financial: [
    permissions.dashboardView,
    permissions.settingsView,
  ],
};
